[network]
name = "simnet"

[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 100000000000000

[accounts.wallet_1]
mnemonic = "spoil sock coyote screen illusion exotic lease resist security post move owner rug enroll remove moral total enroll wallet ruler mango unit soft borrow"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "arrange scale orient half stick situation scale shield process churn pump swap cluster interest work wink never extend shield smile north boost alien woman"
balance = 100000000000000
