name: Clarity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Clarinet
        uses: hirosystems/setup-clarinet@v1
        with:
          clarinet-version: '2.10.0'

      - name: Clarinet Check
        run: clarinet check

      - name: Clarinet Test
        run: clarinet test
