name: Stacks CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Clarinet
        uses: hirosystems/setup-clarinet@v1
        with:
          clarinet-version: 'latest'

      - name: Check contracts
        run: clarinet check

      - name: Run tests
        run: clarinet test

